name = "reject_pvals"
uuid = "c3fb9345-7f27-4466-8933-b77e6f60f162"
authors = ["Gabriel Macé <macegabriel7238@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
MultipleTesting = "0.6.0"
Plots = "1.40.9"
Revise = "3.6.4"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
